name: React Native CI/CD

on:
  push:
    branches:
      - main # Change this to your branch name if needed

jobs:
  build:
    name: Build APK and Upload to Firebase
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js (20.14.0)
        uses: actions/setup-node@v4
        with:
          node-version: '20.14.0'

      - name: Install Dependencies
        run: npm install

      - name: Install Java (OpenJDK 17)
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install Android SDK
        uses: android-actions/setup-android@v3

      - name: Decode Google Services JSON
        run: echo "$FIREBASE_CREDENTIALS" | base64 --decode > android/app/google-services.json
        env:
          FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}

      - name: Grant Permissions for Gradlew
        run: chmod +x android/gradlew

      - name: Clean Android Project
        run: npm run android:clean # Runs `cd android && ./gradlew clean && cd ..`

      - name: Bundle JavaScript for Android
        run: npm run android:bundle # Runs `npx react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res`

      - name: Build APK
        run: npm run android:apk # Runs `cd android && ./gradlew assembleRelease && cd ..`

      - name: Upload APK to Firebase
        run: |
          npm install -g firebase-tools
          firebase appdistribution:distribute android/app/build/outputs/apk/release/app-release.apk \
            --app ${{ secrets.FIREBASE_APP_ID }} \
            --release-notes "This is the release note for the new version." \
            --testers "testers" \
            --token "$(echo $FIREBASE_CREDENTIALS | base64 --decode | jq -r .client_email)"
        env:
          FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}